# Generated by Django 4.0.4 on 2022-05-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knigi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtor', models.CharField(max_length=50)),
                ('zanr', models.CharField(max_length=50)),
                ('godina_izdavanje', models.IntegerField()),
                ('vk_kolicina', models.IntegerField()),
                ('lokacija', models.CharField(max_length=50)),
                ('izdavacka_kukja', models.CharField(max_length=50)),
                ('jazik', models.CharField(max_length=50)),
                ('br_strani', models.IntegerField()),
                ('elektronska_verzija', models.BooleanField()),
                ('elektronski_file', models.FilePathField()),
                ('ISBN', models.CharField(max_length=50)),
                ('naslov_original', models.CharField(max_length=50)),
                ('naslov', models.FloatField()),
                ('kaznena_cena', models.FloatField()),
                ('dali_e_prevedena', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Clen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('data_clenstvo', models.DateField()),
                ('br_clenska_karta', models.IntegerField()),
                ('telefon', models.IntegerField()),
                ('adresa', models.CharField(max_length=50)),
                ('data_raganje', models.DateField()),
                ('aktiven', models.BooleanField()),
                ('datum_clanarina_posledno', models.DateField()),
                ('dali_pozajmeno', models.BooleanField()),
                ('pozajmena_kniga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbiblioteka.knigi')),
            ],
        ),
    ]
