# Generated by Django 4.0.4 on 2022-05-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clen',
            name='pozajmena_kniga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appbiblioteka.knigi'),
        ),
        migrations.AlterField(
            model_name='knigi',
            name='elektronski_file',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
