# Generated by Django 4.0.4 on 2022-05-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblioteka', '0002_alter_clen_pozajmena_kniga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knigi',
            name='elektronski_file',
        ),
    ]
