# Generated by Django 4.0.4 on 2022-05-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblioteka', '0004_knigi_elektronski_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='knigi',
            name='cena',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knigi',
            name='naslov',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
