# Generated by Django 4.0.4 on 2022-05-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblioteka', '0005_knigi_cena_alter_knigi_naslov'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knigi',
            old_name='vk_kolicina',
            new_name='kolicina',
        ),
    ]
