# Generated by Django 4.0.4 on 2022-05-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblioteka', '0008_alter_clen_data_pozajmuvanje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clen',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clen',
            name='telefon',
            field=models.CharField(max_length=50),
        ),
    ]
